# Introducción al Deep Learning 
## Conceptos básicos: Operaciones vectoriales y matriciales

### Propósito 

En el contexto de _Deep Learning_, el álgebra lineal es una herramienta matemática que permite la manipulación de grupos de números simultáneamente a través de operaciones con vectores y matrices. Por ejemplo, las redes neuronales almacenan la información de los pesos del modelo en matrices, por lo que es importante conocer sus operaciones básicas para un entrenamiento y ejecución rápidos y eficientes. También, el uso de vectores y matrices nos permite tratar con grandes volumenes de datos de entrada, como es el caso del procesamiento de imágenes, donde la representación de los pixeles se logra a través de matrices. En este notebook se buscan repasar estas operaciones básicas de álgebra lineal y su aplicación usando la librería _numpy_, donde se revisarán funciones necesarias para el curso.

### Librerías a importar

A continuación se muestran los comandos a ejecutar para poder implementar los procedimientos de este notebook:

In [1]:
import numpy as np

## Vectores y Matrices
Los _vectores_ son arreglos unidimensionales de números, variables o términos. Geométricamente, contienen información sobre la magnitud y dirección de un cambio potencial en un punto. Cuando un vector posee más de una dimensión, se le conoce como una _matriz_. Las matrices más comunes son de dos dimensiones y consisten en un arreglo rectangular de datos, similar a las hojas de cálculo (_spreadsheets_). Entre las formas comunes de representar vectores y matrices, podemos notar las siguientes:
$$
\text{Vectores} \rightarrow 
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
=
\begin{pmatrix}
1 \\
2 \\
3
\end{pmatrix}
=
\begin{Bmatrix}
1 \\
2 \\
3
\end{Bmatrix}	
=
\begin{vmatrix}
1 \\
2 \\
3
\end{vmatrix}
=
\begin{Vmatrix}
1 \\
2 \\
3
\end{Vmatrix}
$$

$$
\text{Matrices} \rightarrow 
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
=
\begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{pmatrix}
=
\begin{Bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{Bmatrix}	
=
\begin{vmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{vmatrix}
=
\begin{Vmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{Vmatrix}
$$

### Dimensiones
Las dimensiones se describen en términos del número de filas y columnas que posee una matriz. Esta definición también se extiende a los vectores, que se pueden entender como matrices de una sola fila y varias columnas, o una sola columna y varias filas. Es importante tener claras las dimensiones de una matriz para poder realizar operaciones consistentes entre arreglos de datos. Para conocer la dimensión de un arreglo en _numpy_, se puede usar la extensión _.shape_ después del arreglo, el cual nos dará un vector con las dimensiones del arreglo.

In [2]:
a = np.array([
 [1,2,3]
])
print("a =", a)
print("Dimensiones de a =", a.shape)

b = np.array([
 [1],
 [2],
 [3]
])
print("b =\n", b)
print("Dimensiones de b =", b.shape)

C = np.array([
 [1,2,3],
 [4,5,6]
])
print("C =\n", C)
print("Dimensiones de C =", C.shape)

a = [[1 2 3]]
Dimensiones de a = (1, 3)
b =
 [[1]
 [2]
 [3]]
Dimensiones de b = (3, 1)
C =
 [[1 2 3]
 [4 5 6]]
Dimensiones de C = (2, 3)


Nótese que el vector $a=[1,2,3]$ tiene dimensiones $(1,3)$, es decir, una fila y tres columnas. El vector $b$ contiene los mismos elementos pero es vertical y tiene tres filas y una columna. Finalmente, la matriz $C$ posee dos filas y tres columnas.

### Operaciones con escalares
Estas operaciones involucran un arreglo de datos y un número el cual puede sumar, restar, multiplicar o dividir cada uno de los elementos del arreglo. A continuación se ejemplifican varias operaciones para un vector $a$ y una matriz $B$:

In [3]:
a = np.array([
 [1,2,3]
])
print("a + 1 =\n", a + 1)
print("a*3 =\n", a*3)

B = np.array([
 [1,2,3],
 [4,5,6]
])
print("B - 2 =\n", B - 2)
print("B/2 =\n", B/2)

a + 1 =
 [[2 3 4]]
a*3 =
 [[3 6 9]]
B - 2 =
 [[-1  0  1]
 [ 2  3  4]]
B/2 =
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]


### Operaciones elemento por elemento
En este tipo de operaciones, los valores de cada posición de un arreglo se suman, restan o multiplican con los de la misma posición en el otro arreglo. Esto implica que, teóricamente, los vectores y matrices a operar deben tener dimensiones iguales.

#### Adición y sustracción
$$
\begin{bmatrix}
a_1 & a_2\\
a_3 & a_4
\end{bmatrix}
\pm
\begin{bmatrix}
b_1 & b_2\\
b_3 & b_4
\end{bmatrix}
=
\begin{bmatrix}
a_1\pm b_1 & a_2\pm b_2\\
a_3\pm b_3 & a_4\pm b_4
\end{bmatrix}
$$

In [4]:
a = np.array([
 [1,2],
 [3,4]])
b = np.array([
 [1,2],
 [3,4]])

print("a + b =\n", a + b)

print("a - b =\n", a - b)

a + b =
 [[2 4]
 [6 8]]
a - b =
 [[0 0]
 [0 0]]


#### Producto externo (Hadamard)
$$
\begin{bmatrix}
a_1 & a_2\\
a_3 & a_4
\end{bmatrix}
\odot
\begin{bmatrix}
b_1 & b_2\\
b_3 & b_4
\end{bmatrix}
=
\begin{bmatrix}
a_1\cdot b_1 & a_2\cdot b_2\\
a_3\cdot b_3 & a_4\cdot b_4
\end{bmatrix}
$$

In [5]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print("Producto de vectores a*b =", a * b)

X = np.array([
 [2,3],
 [2,3]])
Y = np.array([
 [3,4],
 [5,6]])
print("Producto de matrices X*Y =\n", X * Y)

Producto de vectores a*b = [ 2  6 12]
Producto de matrices X*Y =
 [[ 6 12]
 [10 18]]


### Producto punto 
Este tipo de operación algebraica toma dos vectores y retorna un escalar. Sin embargo, puede aplicarse también para matrices, lo que se conoce también como producto matricial. La librería _numpy_ usa la función _np.dot(A,B)_ para operaciones vectoriales y matriciales. Esta operación es una de las más importantes en _deep learning_.

#### Vectorial
$$
\begin{bmatrix}
a_1 & a_2
\end{bmatrix}
\cdot
\begin{bmatrix}
b_1\\
b_2
\end{bmatrix}
=
a_1b_1+a_2b_2
$$

In [6]:
y = np.array([1,2,3])
x = np.array([2,3,4])
print("Producto de punto de vectores x*y =", np.dot(y,x))

Producto de punto de vectores x*y = 20


#### Matricial
En el caso de las matrices, hay que tener en cuenta que no todas las matrices pueden multiplicarse entre sí ya que hay un requerimiento para las dimensiones de las matrices: el número de columnas de la primer matriz debe ser igual al número de filas de la segunda. Como resultado, si multiplicamos una matriz de dimensiones $M\times N$ por otra matriz $N\times K$, obtendremos una matriz de tamaño $M\times K$.
$$
\begin{bmatrix}
a_1 & a_2\\
a_3 & a_4
\end{bmatrix}
\cdot
\begin{bmatrix}
b_1 & b_2\\
b_3 & b_4
\end{bmatrix}
=
\begin{bmatrix}
a_1\cdot b_1+a_2\cdot b_3 & a_1\cdot b_2+a_2\cdot b_4\\
a_3\cdot b_1+a_4\cdot b_3 & a_3\cdot b_2+a_4\cdot b_4
\end{bmatrix}
$$

In [7]:
A = np.array([
 [1, 2],
 [3, 4]
 ])
B = np.array([
 [4, 3],
 [2, 1]
 ])
# Multiply
mm = np.dot(A,B)
print(mm)
print(mm.shape)

[[ 8  5]
 [20 13]]
(2, 2)


### Transpuesta de una matriz
Las redes neuronales procesan frecuentemente pesos y datos de entrada de diferentes tamaños donde las dimensiones no cumplen los requerimientos de la multiplicación de matrices. La transposición de matrices permite rotar una de las matrices (o vectores) de forma que se pueda cumplir con el requerimiento del producto matricial. Para lograr esto, se utiliza la extensión _.T_ al vector o matriz de interés.

In [8]:
b = np.array([
 [1,2,3],
 [4,5,6]
])
print("Dimensiones de b =", b.shape)
b_T = b.T
print("Resultado de b transpuesta =\n", b_T)
print("Dimensiones de b transpuesta =", b_T.shape)

Dimensiones de b = (2, 3)
Resultado de b transpuesta =
 [[1 4]
 [2 5]
 [3 6]]
Dimensiones de b transpuesta = (3, 2)


### Broadcasting en Numpy
En _numpy_, los requerimientos de operaciones elemento por elemento son facilitadas a través de un mecanismo llamado _broadcasting_. Mientras que, por ejemplo, para sumar dos matrices se requiere que estas tengan las mismas dimensiones, este mecanismo también permite realizar operaciones con matrices de diferentes dimensiones mientras una de ellas tenga una dimensión de tamaño 1.

In [9]:
a = np.array([
 [1],
 [2]
])
b = np.array([
 [3,4],
 [5,6]
])
c = np.array([
 [1,2]
])

# Mismo número de filas
# Diferente número de columnas
# pero a tiene una columna, así que funciona por broadcasting
print(a * b)

# Mismo número de columnas
# Diferente número de filas
# pero c tiene una fila, así que funciona por broadcasting
print(b * c)

# Diferente número de columnas
# Diferente número de filas
# pero ambos a y c cumplen la regla de una dimensión
print(a + c)

[[ 3  4]
 [10 12]]
[[ 3  8]
 [ 5 12]]
[[2 3]
 [3 4]]
